version: "1.0"

## Open AI Info

# Open AI API Key
# Live key
openai_api_key: ""

# Open AI Use Override
use_openai: True

## ElasticSearch Info
# This is the index that the search goes out to in elastic. All indexed pages must be under this index.
index_name: "webpage"

elastic_host: "https://localhost:9200"

# This is the number of results the bot will return on search
num_search_results: 3

# These are the projects inside of the search
# Doesn't work yet...
projects:
  - name: Public
  - name: Thesis